language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script: |
  pip install coveralls;
  git clone https://github.com/x4dr/Fen.git ~/wiki;
  coverage run --source . --omit "*venv/*" -m unittest discover --verbose tests;
  coveralls
notifications:
  webhooks: https://nosferatu.vampir.es/travis
